version: '3.6'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: password
      MB_DB_HOST: postgres

  postgres:
    image: postgres:12
    container_name: metabase_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mati@1993
      POSTGRES_DB: metabase
    ports:
      - "5432:5432"